# Generated by Django 6.0.6 on 2026-06-25 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(350.0)], verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('gender', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('nino', 'Niño'), ('unisex', 'Unisex'), ('accesorio', 'Accesorio')], max_length=10, verbose_name='Género / Público')),
                ('style', models.CharField(choices=[('deportivo', 'Deportivo'), ('casual', 'Casual'), ('elegante', 'Elegante'), ('accesorio', 'Accesorio')], max_length=10, verbose_name='Estilo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sizes', models.ManyToManyField(blank=True, to='store.size', verbose_name='Tallas disponibles')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
